name: my_lambda
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  aws_lambda_dart_runtime:
    git: https://github.com/awslabs/aws-lambda-dart-runtime.git
  http: ^0.13.3
  intl: ^0.17.0
  sendgrid_mailer: ^0.1.3
  # mailer: ^5.0.0
  retry: ^3.1.0
dev_dependencies:
  build_runner:
